"""Recreate migrations with TechStack model

Revision ID: 158c3abf5acd
Revises: 
Create Date: 2024-10-23 17:44:56.400768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158c3abf5acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techstack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_techstack',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('techstack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['techstack_id'], ['techstack.id'], name=op.f('fk_user_techstack_techstack_id_techstack')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_techstack_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'techstack_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_techstack')
    op.drop_table('techstack')
    # ### end Alembic commands ###
