"""Add bio, location, and website fields to User model

Revision ID: 19155d1832d3
Revises: 8353eec0ea0c
Create Date: 2024-10-22 17:49:39.236268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19155d1832d3'
down_revision = '8353eec0ea0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
