"""empty message

Revision ID: 4525f322193a
Revises: 47ec2700db63
Create Date: 2024-10-23 16:50:37.597985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4525f322193a'
down_revision = '47ec2700db63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('posted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')

    # ### end Alembic commands ###
