"""empty message

Revision ID: 77002d177c2e
Revises: 19155d1832d3
Create Date: 2024-10-23 14:53:52.293191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77002d177c2e'
down_revision = '19155d1832d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_job_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('desired_job_title')

    # ### end Alembic commands ###
