"""empty message

Revision ID: c5fbde61ad2c
Revises: 4525f322193a
Create Date: 2024-10-23 17:20:23.406531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fbde61ad2c'
down_revision = '4525f322193a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.add_column(sa.Column('job_type', sa.String(), nullable=False, server_default='Full-time'))  # Add default value
        batch_op.add_column(sa.Column('why_choose_us', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role_responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_you', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('employer_questions', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('employer_questions')
        batch_op.drop_column('about_company')
        batch_op.drop_column('about_you')
        batch_op.drop_column('benefits')
        batch_op.drop_column('role_responsibilities')
        batch_op.drop_column('why_choose_us')
        batch_op.drop_column('job_type')
    # ### end Alembic commands ###