"""Remove saved_jobs and applications tables

Revision ID: ffda2c80b4ea
Revises: 6d4ef1b1c7bb
Create Date: 2024-10-23 19:39:32.569717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffda2c80b4ea'
down_revision = '6d4ef1b1c7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_skills_name', ['name'])  # Add unique constraint name

    with op.batch_alter_table('techstack', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_techstack_name', ['name'])  # Add unique constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techstack', schema=None) as batch_op:
        batch_op.drop_constraint('uq_techstack_name', type_='unique')  # Drop constraint by name

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint('uq_skills_name', type_='unique')  # Drop constraint by name

    # ### end Alembic commands ###
